# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce18be01e16edaf46399bbdd3f3699926dfd6e183396181e938a22ffb2a81f7977502913d8cbed8f5940f839abd4bfae65a986222d653fde1393d76db5fa8849

test:
  secret_key_base: bd328549125d44ae7d7aa6f2a7d267933492afec2a184a60e0f71311e6a65e5e3b4eb800d5389738ce774c7f35806875ae0dbac9dae8c6311b223f7ad6b3c7db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
